charts/oes/config/server.xml
charts/oes/templates/oesdb-deployment.yaml
charts/oes/templates/oesdb-pvc.yaml
charts/oes/values.yaml

Changes related to autopilot RHEL images and DB mount path.

Autopilot RHEL based images with DB mount

---

scripts/offline/offline-spinnaker.adoc
scripts/offline/preInstall.sh
scripts/offline/priv-docker-reg.yml
scripts/offline/spin-cp2hal.sh
scripts/offline/spin-deployhal.sh
scripts/offline/spin-docker-load.sh
scripts/offline/spin-docker-save.sh
scripts/offline/spin-getbom.sh
scripts/offline/spin-gethelm.sh
scripts/offline/spin-offline.sh
scripts/offline/spin-pv.yaml

Includes the Offline spinnaker installation scripts and the Document

Offline Spinnaker installation procedure

---

charts/oes/Chart.yaml
charts/oes/README.md
charts/oes/config/oes-gate-config/gate.yml
charts/oes/config/sapor-config/spinnaker.yaml
charts/oes/templates/oes-gate-deployment.yaml
charts/oes/templates/oes-gate-service.yaml
charts/oes/templates/oes-sapor-deployment.yaml
charts/oes/templates/oes-sapor-service.yaml
charts/oes/templates/oes-ui-deployment.yaml
charts/oes/templates/oes-ui-service.yaml
charts/oes/templates/opa-service.yaml
charts/oes/values.yaml
charts/opsmx-autopilot/Chart.yaml
charts/opsmx-autopilot/config/config.properties
charts/opsmx-autopilot/config/hibernate.cfg.xml
charts/opsmx-autopilot/values.yaml
scripts/oes-autoconfig/Dockerfile
scripts/oes-autoconfig/README.txt
scripts/oes-autoconfig/config_endpoint.sh

@Nirmalyasen , please review.
cc @ksrinimba 
Change log:
- Add init container to automatically configure OES in unrestricted environments where LB is available.
- Fix bugs in oes values.yaml
- Update configuration files of autopilot
- Add script and corresponding Dockerfile for init container

Add scripts to auto configure OES via init container & fix minor bugs

---

charts/oes/values.yaml

- Update images to incorporate new features related to
i. Manual Judgement
ii. OPA policy configurations
iii. Option to specify spinnaker authn in sapor

Update OES images

---

README.md

@ksrinimba & @vkvamsiopsmx FYI, please

Update README.md file with OES & Autopilot installation instructions

---

README.md
charts/oes/README.md

- Helm 2.x will be deprecated on Nov 13 2020

Remove helm2 references

---

scripts/easy-spinnaker/inst_oes.sh

Install just spinnaker with easy-spinnaker solution

---

charts/oes/charts/spinnaker/templates/configmap/halyard-overrideurl.yaml
charts/oes/templates/spinnaker-extra/spinsvcs.yaml
charts/oes/values-oss.yaml
charts/oes/values.yaml

- Bump deck image to 3.3 to fix issues with 3.2
- Increase default timeout of autoconfig to 180s
- Add labels to deck, gate LB services

Add additional ldap groups

---

charts/oes/charts/spinnaker/templates/configmap/halyard-overrideurl.yaml
charts/oes/values.yaml

- Configure max delay to fetch Load Balancer IPs of
spin-deck and spin-gate and substitute in hal config

Parameterize max delay for fetching LBs

---

charts/oes/templates/rbac/oes-init-rolebinding.yaml
scripts/oes-autoconfig/config_endpoint.sh
scripts/oes-autoconfig/config_overrideurl.sh

- Autoconfig init container issue fixed
to fetch nodeport IP
- Increase max allowed timeout to 8.3 mins

Fix auto config issue

---

charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/values.yaml

- Change oes-init image repo to opsmxdev/oes-init
- Change default image pull policy to IfNotPresent

Move oes-init image to opsmxdev

---

charts/oes/config/oes-sapor/application.yml
charts/oes/values.yaml

Add new configurable option to sapor

---

charts/oes/templates/deployments/oes-autopilot-deployment.yaml
charts/oes/templates/deployments/oes-dashboard-deployment.yaml
charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/deployments/oes-sapor-deployment.yaml
charts/oes/templates/deployments/oes-visibility-deployment.yaml
charts/oes/values.yaml

Customized Resources

---

charts/oes/templates/secrets/opsmx-gitops-secret.yaml

- To avoid specifying secrets in base64 format

Change secret data type to stringData

---

charts/oes/charts/spinnaker/config/orca-local-pipeline-promotion.yml
charts/oes/charts/spinnaker/config/orca-local.yml

Removed the old Custom policy and Enhanced it as the Policy stage with more input parameters and dedicated image with more modification as Suggested by Vasantha

Policy enhanced

---

charts/oes/charts/spinnaker/config/orca-local-pipeline-promotion.yml
charts/oes/charts/spinnaker/config/orca-local.yml

Modified the orca file to extract the SPINNAKER_PROPERTY (STATUS & Response URL)and also modified the script in the image not to failure the Visibility at Rejected Status and passing it to next stage to take decesion on failure based on status

Visibility added propertyfile

---

charts/oes/charts/spinnaker/config/orca-local-pipeline-promotion.yml
charts/oes/charts/spinnaker/config/orca-local.yml

This is new stage created as a feature of  3.6 release

Test verificationstage added

---

charts/oes/Chart.yaml
charts/oes/charts/spinnaker/templates/configmap/spin-pipeline-import.yaml
charts/oes/templates/_helpers.tpl
charts/oes/templates/ingress/oes-gate-ingress.yaml
charts/oes/templates/ingress/oes-ui-ingress.yaml

- Address issues in init container to create sample pipelines in spinnaker
- Allow http termination at oes ingress

Fix issues in ingress templates

---

charts/oes/charts/spinnaker/config/orca-local.yml
charts/oes/values.yaml

I assume not to expose OpsMx credentials over Helm chart to the users

JIRA stages are aligned under webhook and remove Credentials 

---

charts/oes/config/oes-sapor/application.yml

Added Halyard Restart Webhook Tag - GitOps Related

Added Restart Webhook Tag for halyard

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/values.yaml

Reverts OpsMx/enterprise-spinnaker#122

Revert "provide option to specify environment"

---

charts/oes/charts/spinnaker/config/orca-local.yml

Improved the image with additional featured and added parameters in orca file did  versioning on image 3.7

Enhanced the policy,verification,visibility parameters and included version tag and generic names for parallel  run jobs

---

charts/oes/charts/spinnaker/config/orca-local.yml

Also removed unwanted info requested by Vasantha

Added the Custom Connector Parameters

---

charts/oes/charts/spinnaker/config/orca-local.yml

These are the UI modifications that are suggested by the Vasantha

re-aligned the parameters and label correction

---

charts/oes/Chart.yaml
charts/oes/charts/spinnaker/templates/ingress/deck.yaml
charts/oes/charts/spinnaker/templates/ingress/gate.yaml
charts/oes/templates/ingress/oes-gate-ingress.yaml
charts/oes/templates/ingress/oes-ui-ingress.yaml
charts/oes/values.yaml

https://github.com/helm/helm/issues/9696

Add ssl flag to overcome a bug in helm

---

charts/oes/charts/spinnaker/config/orca-local.yml

Changed imagepull policy from Always to IfNotPresent

Changed the imagepullpolicy based on srini suggestion

---

charts/oes/templates/hooks/cleanup.yaml
charts/oes/templates/ingress/oes-gate-ingress.yaml
charts/oes/templates/ingress/oes-ui-ingress.yaml
charts/oes/values-stash.yaml

Suggested ingress name instead of prepending the RELEASE-NAME.
simple same ingress name for releases.
ingress of gate and ui have change suggestions.

Rename oes ingress resources

---

charts/oes/Chart.yaml
charts/oes/values.yaml

Update helm chart for OES 3.8.1

---

charts/oes/Chart.yaml
charts/oes/values.yaml

Update helm chart for 3.8.1.1

---

charts/oes/Chart.yaml
charts/oes/values.yaml

Please review the changes and approve. Thanks!

OES v3.8.2 release

---

charts/oes/Chart.yaml
charts/oes/values.yaml

Please review my changes and approve the PR

OES release - image version updates

---

scripts/oes-data-migration-scripts/migration_v3.8.x_to_v3.9.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.8.x_to_v3.9.txt

https://devopsmx.atlassian.net/browse/OP-7058

OP-7058: Added sapor db migration table alter for cloud configuration

---

scripts/oes-data-migration-scripts/migration_v3.8.x_to_v3.9.py

https://devopsmx.atlassian.net/browse/OP-7058

Made some changes

---

scripts/oes-data-migration-scripts/migration_v3.8.x_to_v3.9.py

https://devopsmx.atlassian.net/browse/OP-7174

script modified

---

charts/oes/templates/pipeline-promotion/pipe-promot-config-cm.yaml
charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml

pipeline promotion fix for s3 bucket

s3 pipeline promotion fix

---

scripts/oes-data-migration-scripts/migration_v3.8.x_to_v3.9.py

https://devopsmx.atlassian.net/browse/OP-7205

Migration script issue fix

---

charts/oes/config/oes-gate/gate.yml

cors issue fix

---

charts/oes/config/oes-dashboard/dashboard-local.yml
charts/oes/templates/services/oes-gate-service.yaml
charts/oes/templates/services/oes-ui-service.yaml
charts/oes/templates/spinnaker-extra/spinsvcs.yaml

Changed the Files OES UI, Gate and spinnaker extra services to support Nodeport. Dashboard config changed to retrieve the spinnaker URL for NodePort

K8sServiceType Nodeport Introduced

---

charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml

This is the functionality where the spinnaker will backup all applications and pipelines to the git repo when the user runs the backup pipeline without any input provided using pipeline promotion.

backup all pipe if user not specify input in pipe-promot

---

README.md
charts/oes/README.md
charts/oes/charts/spinnaker/templates/ingress/deck.yaml
charts/oes/charts/spinnaker/templates/ingress/gate.yaml
charts/oes/templates/ingress/oes-gate-ingress.yaml
charts/oes/templates/ingress/oes-ui-ingress.yaml
charts/oes/templates/spinnaker-extra/ingress.yml

https://kubernetes.io/docs/concepts/services-networking/ingress/#resource-backend

Upgrade ingress apiVersion

---

charts/oes/charts/spinnaker/config/orca-local.yml

Labels are added in order to delete the job with labels as REF

added lables for the customstage

---

charts/oes/charts/spinnaker/config/orca-local.yml
charts/oes/templates/spinnaker-extra/spinsvcs.yaml

Removal of extra name and ports for spin gate lb and spin deck lb in spinsvc.yaml
Added labels for custom stage and changes done in orcal local.yaml

Removing the extra ports and names in the spinsvc.yaml and Added labels for custom stage

---

charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml

sync all the applications, if the user not specify in the input of pipelineparaamter

added the sync all apps feature if user not specify input

---

charts/oes/charts/spinnaker/config/orca-local.yml
charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml
charts/oes/config/oes-gate/gate.yml
charts/oes/templates/_helpers.tpl
charts/oes/templates/clouddriver-sidecar/k8sconfig-sync.yaml
charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/deployments/oes-sapor-deployment.yaml
charts/oes/templates/deployments/oes-visibility-deployment.yaml
charts/oes/templates/forwarder/create-controller-secret.yaml
charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml
charts/oes/values.yaml

Aligned the code as per oes3.9 branch
Added the Kayanta changes in values.yaml
Added the cloud-driver sidecar changes

Alignchangesfrom3.9to3.10

---

charts/oes/templates/secrets/opsmx-gitops-secret.yaml

dynamic account repository parameter added in the secrets which is inherited by k8config-sync cm

Updating the dynamic account repository

---

charts/oes/Chart.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/values.yaml

Also fixed a bug related to theAP-UI not coming up.

Oes3.10.1 version update

---

scripts/oes-data-migration-scripts/migration_v3.10.x_to_v3.11.py
scripts/oes-data-migration-scripts/migration_v3.9.x_to_v3.10.py
scripts/oes-data-migration-scripts/step_to_migrate_from_v3.9.x_to_v3.10.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.10.x_to_v3.11.txt

https://devopsmx.atlassian.net/browse/OP-10690

worked on audit service data

---

charts/oes/Chart.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml
charts/oes/values.yaml

1. Updating all the images to v3.9.5.5
2. Changes in the mount path for oes ui
3. Updating the application version to v3.9.5.5

Updated the images to v3.9.5.5

---

charts/oes/config/oes-audit/audit-client-local.yaml
charts/oes/config/oes-audit/audit-local.yaml
charts/oes/config/oes-datascience/app-config.yml
charts/oes/config/oes-platform/platform-local.yml
charts/oes/config/oes-sapor/application.yml
charts/oes/config/oes-visibility/visibility-local.yml
charts/oes/templates/deployments/oes-audit-client.yaml
charts/oes/templates/deployments/oes-audit-service.yaml
charts/oes/templates/deployments/oes-autopilot-deployment.yaml
charts/oes/templates/deployments/oes-datascience-deployment.yaml
charts/oes/templates/deployments/oes-visibility-deployment.yaml
charts/oes/templates/pipeline-promotion/git-token-secret.yaml
charts/oes/templates/pipeline-promotion/local-spin-cli-config-secret.yaml
charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml
charts/oes/templates/pipeline-promotion/spin-cli-config-secret.yaml
charts/oes/templates/secrets/oes-audit-client-secret.yaml
charts/oes/templates/secrets/oes-audit-service-secret.yaml
charts/oes/templates/secrets/oes-autopilot-secret.yaml
charts/oes/templates/secrets/oes-datascience-secret.yaml
charts/oes/templates/secrets/oes-visibility-secret.yaml

*  Added quotes to all usernames and password
* Changed cm to secrets of visibility,auditclient,auditservice,datascience
* Added installSpinnaker flag to pipeline promotion files

Change cm to secrets of visibility,auditclient,auditservice,datascience

---

charts/oes/charts/spinnaker/config/orca-local.yml
charts/oes/config/oes-audit/audit-client-local.yaml
charts/oes/config/oes-audit/audit-local.yaml
charts/oes/config/oes-dashboard/dashboard-local.yml
charts/oes/config/oes-datascience/app-config.yml
charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-ui/app-config.json
charts/oes/config/oes-ui/help-text.json
charts/oes/templates/configmaps/oes-ui-configmap.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/values.yaml

Changes made in the configmaps of the below services:
1. Audit (Added the admin user in the audit client and server cm)
2. Dashboard (Added the gate service to dashboard)
3. Gate (Increased the retrofit timeout)
4. Datascience (Added the username/password for the rabbitmq)
5. oes-ui (Added the help text for all the UI components)
Spinnaker Changes:
1. orca-local.yml (Added the OPA Policy for app creation and also the rbac plugins)

OES3.11 Release

---

charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-platform/platform-local.yml

1. Added a flag for installation mode in gate.
2. Gate url added in platform.

Configuration changes in gate,platform

---

scripts/oes-data-migration-scripts/migration_v3.9.x_to_v3.10.py
scripts/oes-data-migration-scripts/step_to_migrate_from_v3.9.x_to_v3.10.txt

https://devopsmx.atlassian.net/browse/OP-12456

OP-12456: migration url input

---

scripts/oes-data-migration-scripts/migration_v3.9.x_to_v3.10.py
scripts/oes-data-migration-scripts/step_to_migrate_from_v3.9.x_to_v3.10.txt

https://devopsmx.atlassian.net/browse/OP-12456

OP-12456: worked on v3.9 to v3.10 scirpt change to take url as input

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml
charts/oes/templates/pipeline-promotion/git-token-secret.yaml
charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml
charts/oes/values.yaml

implemented ssh key based authentication for git clone
changes done:
-  added the init container for the SSH key based clone in halyard sts
- modified the halyard init script
- updated the aws git image in the init container (awsgit:v2-openssh)
Pipeline Promotion
- implemented the **git ssh key** in **git-token** secret
- added branch and ssh functionality in pipelinepromotion configmap
- added ssh instructions to pipelinepromotion in values.yaml

SSH key and ssh based authentication in clouddriver to 3.10

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/config/sapor-gate/gate-local.yml

This change gets it sapor-gate to work even with RBAC enabled.

Updated the credentials so that it works with RBAC

---

scripts/oes-data-migration-scripts/migration_v3.11_to_v3.11.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11_to_v3.11.x.txt

https://devopsmx.atlassian.net/browse/OP-12747

Added alter table function for metric details table.

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

https://devopsmx.atlassian.net/browse/OP-11259

added migration script v3.11.x to v3.12

---

charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml

added the save path functionality

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py

https://devopsmx.atlassian.net/browse/OP-12889

OP-12889:bug:Not displaying the standard error code for deleting metric template

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

https://devopsmx.atlassian.net/browse/OP-13330

OP-13330: script changes

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

https://devopsmx.atlassian.net/browse/OP-13330

OP-13330: worked on script fix

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py

https://devopsmx.atlassian.net/browse/OP-13481

update custom gate url issue

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py

https://devopsmx.atlassian.net/browse/OP-13481

migration script issue resolved

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py

https://devopsmx.atlassian.net/browse/OP-13481

migration script issue

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/config/oes-ui/help-text.json
charts/oes/config/sapor-gate/gate-local.yml
charts/oes/config/sapor-gate/gate.yml
charts/oes/templates/configmaps/datasource-creation.yaml
charts/oes/values.yaml

1. ISD 3.12.1 Config changes
2. Added rbac flag for autoconfiguration.
3. Removal of override spinnaker namespace for clouddriver local yml

ISD 3.12.1 releaseconfig changes and modifications in autoconfiguration

---

charts/oes/charts/openldap/templates/deployment.yaml
charts/oes/charts/redis/templates/redis-master-statefulset.yaml
charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml
charts/oes/templates/_helpers.tpl
charts/oes/templates/deployments/oes-audit-client.yaml
charts/oes/templates/deployments/oes-audit-service.yaml
charts/oes/templates/deployments/oes-autopilot-deployment.yaml
charts/oes/templates/deployments/oes-dashboard-deployment.yaml
charts/oes/templates/deployments/oes-datascience-deployment.yaml
charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/deployments/oes-rabbitmq-deployment.yaml
charts/oes/templates/deployments/oes-sapor-deployment.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/templates/deployments/oes-visibility-deployment.yaml
charts/oes/templates/deployments/opa-deployment.yaml
charts/oes/templates/forwarder/oes-forwarder-deployment.yaml
charts/oes/templates/hooks/github-create.yaml
charts/oes/templates/hooks/oes-config-job.yaml
charts/oes/templates/sapor-gate/sapor-gate-deployment.yaml
charts/oes/templates/statefulsets/oes-db-statefulset.yaml
charts/oes/values.yaml

1. Added spinnaker components in redis,opa,openldap microservices.
2. Added spinnaker components in all oes components.
3. Added spinnaker for autoconfiguration and github repo creation jobs.

Added Spinnaker annotations in OES Components

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml

1. Corrected the bootstrap token extraction using the yq 
2. Added new image awsgit:v2-openssh-javalibs which has new Decryptor jar added source code https://github.com/OpsMx/custom-stages/tree/main/awsgit/v2-openssh-javalibs
3. Configuring the JIRA to orca-local.yaml by extracting the secret which is created by halyard and pass those variables to orca-local.yaml

Jira integration and bootstrap decrypt  token extraction

---

charts/oes/charts/prometheus/config/node_alerting_rules.yml
charts/oes/charts/prometheus/config/spin_alerting_rules.yml

1) Modified node_alerting_rules.yml
2) Modified spin_alerting_rules.yml

modified alert definitions

---

charts/oes/config/oes-audit/audit-client-local.yaml
charts/oes/config/oes-platform/platform-local.yml
charts/oes/config/oes-ui/help-text.json
charts/oes/templates/configmaps/datasource-creation.yaml
charts/oes/templates/configmaps/standard-error-codes.yaml
charts/oes/templates/sapor-gate/sapor-gate-deployment.yaml

1. Updated the help text as per v3.12.5
2. Modified the auto configuration script for gitlab as a source provider.
3. Added the imagePullSecrets for saporgate.
4. Removed the admin user for platform and audit service

ISD Release v3.12.5

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/migration_v3.12.4_to_v3.12.5.py
scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.4_to_v3.12.5.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-15942

OP-15942:v4.0:enterprise repo:Added and modified migration scripts for verification-delete_log_template issue

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-15796 : ref Id Updated

Updated the RefId in script

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/migration_v3.12.5_to_v3.12.6.py
scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.5_to_v3.12.6.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-16310

OP-16310- migration script v3.12.5 to v3.12.6

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-16133

Made changes to add cluster info

---

scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.4_to_v3.12.5.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.5_to_v3.12.6.txt

https://devopsmx.atlassian.net/browse/OP-16462

bugfix/OP-16462-master:correct version and script parameters in upgrade scripts

---

README.md
charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/config/oes-gate/gate.yml

Corrected the yq commands in the halyard init script

Admin configuration correction and readme file correction

---

README.md
charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-platform/platform-local.yml
charts/oes/config/sapor-gate/gate-local.yml
charts/oes/values.yaml

values.yml
charts/spinnaker/templates/configmap/halyard-init-script.yaml
config/oes-platform/platform-local.yml
config/sapor-gate/gate-local.yml
README.md

admin group configuration to global, fixed openshift ldap related issue

---

charts/oes/charts/spinnaker/templates/configmap/spin-pipeline-import.yaml

1. Wait time for 100 sec to be service pods running state 1/1
2. Clone failure error handled
3. Pipeline save error handle if spincli is not authenticated properly with loop run to try for three times

Added wait time for pipeline save and handle error with loop retry

---

scripts/oes-data-migration-scripts/migration_v3.10.x_to_v3.11.py
scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.10.x_to_v3.11.txt
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-16891: worked on script updation logging and db username input

---

scripts/oes-data-migration-scripts/migration_v3.10.x_to_v3.11.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.10.x_to_v3.11.txt

OP-16891: migration script updated with logging info and db user input

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-16891: migration script v3.12 to v4 update

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

Jira - https://devopsmx.atlassian.net/browse/OP-16892

OP-16892 : 3.11 To 3.12 DB Migration Script Changes.

---

scripts/oes-data-migration-scripts/migration_v3.9.x_to_v3.10.py
scripts/oes-data-migration-scripts/step_to_migrate_from_v3.9.x_to_v3.10.txt

https://devopsmx.atlassian.net/browse/OP-16820

modified the script to execute pre-upgradation

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-16891: migration script updation v4.0

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-16891: worked on migration script v4.0 updatation

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

https://devopsmx.atlassian.net/browse/OP-16964

cookie replaced with username/password

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.11.x_to_v3.12.txt

https://devopsmx.atlassian.net/browse/OP-16964

Op 16964 replace cookie arg v3.11

---

scripts/oes-data-migration-scripts/migration_v3.9.x_to_v3.12.x_audit_data.py

https://devopsmx.atlassian.net/browse/OP-16968

masked the credentials

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-16891: migration script v3.12 to v4.0 updated

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-16497

OP-16891: worked on migration update

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

worked on OP-16891_migration_v3.12_to_v4

---

scripts/oes-data-migration-scripts/clean_unused_audit_data.py
scripts/oes-data-migration-scripts/steps_to_clean_unused_audit_data

Jira - https://devopsmx.atlassian.net/browse/OP-16990

OP-16990 : Script For Cleaning Unused Audit Events Data From Audit Database

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-17004 migration_sapor_url input

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-17064

added logic to populate location column

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

worked on migration Script updation

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

worked on migration Script updation phase2

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

worked on migration Script updation phase3

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-16497

worked on migration Script updation phase4

---

scripts/oes-data-migration-scripts/migration_v3.11.x_to_v3.12.py

https://devopsmx.atlassian.net/browse/OP-17031

handled the pod url

---

charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml
charts/oes/config/oes-ui/help-text.json
charts/oes/templates/configmaps/standard-error-codes.yaml
charts/oes/values.yaml

1. Halyard image updated and sts post install cmd changes
2. forwarder images update as per 4.0

Image changes as per ISD v4.0

---

charts/oes/Chart.yaml
charts/oes/charts/minio/templates/deployment.yaml
charts/oes/charts/minio/templates/post-install-create-bucket-job.yaml
charts/oes/charts/minio/templates/post-install-prometheus-metrics-job.yaml
charts/oes/charts/minio/templates/statefulset.yaml
charts/oes/charts/spinnaker/templates/deployments/create-sample-job.yaml
charts/oes/charts/spinnaker/templates/hooks/install-using-hal.yaml
charts/oes/charts/spinnaker/templates/statefulsets/halyard.yaml
charts/oes/templates/deployments/oes-audit-client.yaml
charts/oes/templates/deployments/oes-audit-service.yaml
charts/oes/templates/deployments/oes-autopilot-deployment.yaml
charts/oes/templates/deployments/oes-dashboard-deployment.yaml
charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/deployments/oes-rabbitmq-deployment.yaml
charts/oes/templates/deployments/oes-sapor-deployment.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/templates/deployments/opa-deployment.yaml
charts/oes/templates/hooks/cleanup.yaml
charts/oes/templates/hooks/oes-config-job.yaml
charts/oes/templates/sapor-gate/sapor-gate-deployment.yaml
charts/oes/templates/statefulsets/oes-db-statefulset.yaml
charts/oes/values.yaml

1. Disabled security context for all services in OpenShift.
2. Added default env for halyard sts in for Open Shift.

Helm Chart Compatible for Kubernetes and OpenShift 

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-17233

audit source migration

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-17233

converting the index from double to integer

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-17233

stageJson initialized with None

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-17270

removed the limit from select pipeline

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-17368

Op 17368 v4.0

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-17617

OP-17368: bytes to string so that will be compatible with db datatypes.

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml
charts/oes/config/oes-autopilot/autopilot.properties
charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-platform/platform-local.yml
charts/oes/config/oes-sapor/application.yml
charts/oes/config/oes-visibility/visibility-local.yml

1. Removed the dependency of External url in ISD services
2. Bug fix for https://opsmx.freshdesk.com/a/tickets/1807

Removed the dependency of External url

---

charts/oes/config/oes-autopilot/autopilot.properties
charts/oes/config/oes-visibility/visibility-local.yml
charts/oes/values.yaml

This reverts commit 567f38b484e9981150c02210ca526d81b5170570.

Revert "Updated the ISD v4.0.1 config changes"

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-18806

OP-18806 : Updated 3.12.x to 4.0 python migrating script

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-18991

OP-18991 : Added DB Schema version to DB

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-18990
[OP-18990]: https://devopsmx.atlassian.net/browse/OP-18990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-18990: Implemented to support Spinnaker use backend SQL DB

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-OP-18385: Bugfix for migration script with audit source details table

---

scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-19026

OP-19026: Added the comments for migration flag DB upgrade process

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-18385: Implemented use internal service host instead of isd gate url and commongate option

---

scripts/logs-backup-from-all-pods/get-all-pod-logs.sh
scripts/logs-backup-from-all-pods/log-extractor-instructions.txt

Reverts OpsMx/enterprise-spinnaker#440

Revert "modified script to work when multiple containers present"

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: bugfix for Policy and service id not available

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: bugfix for Platform api call for approval gate group information

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

OP-18385: bugfix for autopilot and visibility call for connector and template names

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-19199

OP-19199: implemented the DB Schema version to verify in post DB upgrade run

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-19199

OP-19199: Bugfix for the DB Schema version to verify in post DB upgrade run

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-19253

enabled auto commit

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml

If bom file is located in the gitops repo  like https://github.com/OpsMx/standard-gitops-repo/blob/v4.0.3/bom
1. It will change the halyard version from the bom file 
2. It will change the service-settings service artifact image  from bom 
https://devopsmx.atlassian.net/browse/OP-19063

Handle bom file in halyard init script - OP-19063

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py
scripts/oes-data-migration-scripts/steps_to_migrate_from_v3.12.x_to_v4.0.x.txt

https://devopsmx.atlassian.net/browse/OP-19252

OP-19252: Implementation for spinnaker uses postgres

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

https://devopsmx.atlassian.net/browse/OP-19252

OP-19252: Bugfix for db version delete

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: Bugfix for redis db connection

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: Bugfix for spinnaker cookie activate

---

charts/oes/templates/pipeline-promotion/pipe-promot-scripts-cm.yaml

https://github.com/OpsMx/custom-stages/pull/8

modified script to default branch if user does not specify - OP-19548

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: Bugfix for logging the parameters and changes statements

---

scripts/oes-data-migration-scripts/migration_v3.12.x_to_v4.0.x.py

OP-18385: Bugfix for optimize the sql query for gate executions to fetch

---

scripts/logs-backup-from-all-pods/extract_logs.py
scripts/logs-backup-from-all-pods/get-all-pod-logs.sh
scripts/logs-backup-from-all-pods/log-extractor-instructions.txt

OP-18601: script changes to fetch logs/counts.

---

scripts/logs-backup-from-all-pods/extract_logs.py
scripts/logs-backup-from-all-pods/get-all-pod-logs.sh
scripts/logs-backup-from-all-pods/log-extractor-instructions.txt

OP-18601: Cherry-pick commit from master

---

scripts/logs-backup-from-all-pods/extract_logs.py
scripts/logs-backup-from-all-pods/get-all-pod-logs.sh

OP-18601: handled sql case

---

scripts/logs-backup-from-all-pods/extract_logs.py

OP-18601: Handled sql and datetime issues

---

charts/oes/rc-images-values.yaml

@saitejaopsmx I just updated the v4.0.4.b2 images into rc-images yaml file. 
Please review and merge it.

v4.0.4.b2 images

---

charts/oes/config/oes-platform/platform-local.yml
charts/oes/rc-images-values.yaml
charts/oes/templates/configmaps/isd-feature-flag-config.yml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/forwarder/create-controller-secret.yaml

Made the changes to v4.0.4.b3 helm

v4.0.4.b3 helm changes

---

scripts/logs-backup-from-all-pods/extract_logs.py

Op 18601 db port optnl

---

charts/oes/config/oes-platform/platform-local.yml
charts/oes/templates/configmaps/isd-feature-flag-config.yml
charts/oes/templates/forwarder/create-controller-secret.yaml
charts/oes/values.yaml

Create-controller-secret:  https://devopsmx.atlassian.net/browse/OP-20175
DB cleanup configuration changes: https://devopsmx.atlassian.net/browse/OP-20003
ISD4.0.4.b4-rc1 images updation: https://devopsmx.atlassian.net/browse/OP-19842
@saitejaopsmx Please review and merge this PR

Helm changes for v4.0.4.b4-rc1

---

charts/oes/config/oes-platform/platform-local.yml
charts/oes/templates/_helpers.tpl
charts/oes/templates/configmaps/isd-feature-flag-config.yml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/forwarder/create-controller-secret.yaml
charts/oes/values.yaml

v4.0.3.1 related images/config/secret/opa/controller-secret changes

V4.0.3.1 rc1 changes

---

charts/oes/values.yaml

Updated the audit-service image to latest RC5 tag in values.yaml

Audit-service image to latest RC5 tag

---

charts/oes/config/oes-audit/audit-local.yaml
charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-ui/help-text.json
charts/oes/templates/configmaps/standard-error-codes.yaml
charts/oes/values.yaml

Updated all v4.0.4 related image and config changes.
List of config changes reference url's:
1. Help Text changes:
https://github.com/OpsMx/kubeyaml/commit/6e2cbfbe71885d3bdef2bda5f8d896f3449e25d4
2. Audit-service: DB migration related flag introduced
https://github.com/OpsMx/kubeyaml/commit/7985c2dee840f7ce7ec9c74258ec993b677b7a67
3. Gate secret change:
https://devopsmx.atlassian.net/browse/OP-20271

Updated all v4.0.4 related image and config changes

---

charts/oes/values.yaml

[OP-20482: feature implementation for GCP account validation](https://devopsmx.atlassian.net/browse/OP-20482)

v4.0.3.1 - OP-20482: feature implementation for GCP account validation

---

charts/oes/values.yaml

https://github.com/OpsMx/gate/pull/379
[@Giribabu T](https://opsmx.slack.com/team/UM4PT1137)
- Once this PR is merged we need to take another RC for GATE service
[#379 Bypassing the RBAC check for create gate and update gate APIs](https://github.com/OpsMx/gate/pull/379)

V4.0.3.1 - Bypassing the RBAC check for create gate and update gate APIs

---

charts/oes/config/oes-ui/help-text.json
charts/oes/values.yaml

https://devopsmx.atlassian.net/browse/OP-20403

V4.0.4 - ISD images and other configurations OP-20403

---

charts/oes/values.yaml

1. OP-20562: Create a policy for with non admin user #177 (Nagendra / Aravind)
2. OP-20560: made save source details part Synchronized to fix unique key constraint violation. #135
3. Back ported the rbac related fixes (from Sudhakar)

v4.0.3.1 related RC images - values.yaml

---

charts/oes/values.yaml

[OP-19842](https://devopsmx.atlassian.net/browse/OP-19842) Update helm with 4.0.3.1 images
[OP-19842]: https://devopsmx.atlassian.net/browse/OP-19842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

For all OES services images updated with prod tags

---

charts/oes/Chart.yaml

1. Opa fixes
2. Improvements in loading the ISD pages
3. Create Pipeline using Pipeline Template with ISD Gates.
4. Implement and enforce data retention policy for ISD database

Helm Chart release for v4.0.3.1

---

charts/oes/charts/spinnaker/templates/configmap/halyard-init-script.yaml

https://devopsmx.atlassian.net/browse/OP-20825

Updated the Jira On Prem changes OP-20825

---

charts/oes/config/oes-gate/gate.yml

OP-20403: Helm chart update for v4.0.4 release
@saitejaopsmx I did a mistake while updating gate config changes. As part of upgrade testing I found this. So I fixed it. 
Please review and merge this change. For now I have fixed it manually in QA instances. Thank you

fixed the gate config - indentation issue of user: {}

---

charts/oes/config/oes-ui/help-text.json
charts/oes/config/oes-visibility/visibility-local.yml
charts/oes/values.yaml

[OP-20403](https://devopsmx.atlassian.net/browse/OP-20403): v4.0.4 Helm changes 
[OP-20403]: https://devopsmx.atlassian.net/browse/OP-20403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

v4.0.4 latest RC images and Config changes

---

charts/oes/charts/spinnaker/templates/configmap/spin-pipeline-import.yaml
charts/oes/charts/spinnaker/templates/job/create-sample-job.yaml
charts/oes/config/oes-gate/gate.yml

https://devopsmx.atlassian.net/browse/OP-20960

Updated the Image and the Script

---

charts/oes/values.yaml

v4.0.4 production image update

OP-20403: v4.0.4 production images updated

---

charts/oes/Chart.yaml
charts/oes/templates/sapor-gate/sapor-gate-deployment.yaml
charts/oes/templates/sapor-gate/sapor-gate-secret.yaml

1.Enabling/Disabling the pipelinelevel RBAC
2.Add support to display deployments through Jenkins deploy stage
3. PubSub Integrator should have templatePath as an optional field in ISD integrations page

ISD v4.0.4 Release

---

charts/oes/config/oes-audit/audit-local.yaml
charts/oes/values.yaml

Parameterized the DB migration configuration values.

Parameterized the DB migration configurations

---

charts/oes/values.yaml

Updated the image tags to v4.0.4.1 production tags

updating image tags to prod

---

charts/oes/charts/grafana/values.yaml
charts/oes/charts/prometheus/values.yaml
charts/oes/values.yaml

Updated the images to v4.0.4.2-rc1

Updating pvc for prom and grafana

---

charts/oes/config/oes-ui/app-config.json
charts/oes/values.yaml

Added below code in app-config.json
```
"triggerPipeline": false,
"cdTool": "Spinnaker",
```

ui config changes

---

charts/oes/config/oes-audit/audit-local.yaml
charts/oes/config/oes-ui/app-config2.json
charts/oes/templates/configmaps/oes-ui-configmap.yaml

Disabled opentelemetry in audit service

Adding oes-ui changes wrt grafana

---

charts/oes/config/oes-ui/app-config2.json
charts/oes/values.yaml

quay.io/opsmxpublic/ubi8-oes-ui:v4.0.4.2-rc5
quay.io/opsmxpublic/ubi8-oes-audit-client:v4.0.4.2-rc4
quay.io/opsmxpublic/ubi8-oes-platform:v4.0.4.2-rc4
quay.io/opsmxpublic/ubi8-oes-sapor:v4.0.4.2-rc4

Updating rc4 images

---

charts/oes/config/sapor-gate/gate.yml

added auditserice dashboard and spring block of code

Updated the sapor-gate of  gate.yml configuration

---

charts/oes/Chart.yaml
charts/oes/config/oes-gate/gate.yml
charts/oes/config/oes-ui/nginx.conf
charts/oes/templates/deployments/oes-audit-client.yaml
charts/oes/templates/deployments/oes-audit-service.yaml
charts/oes/templates/deployments/oes-autopilot-deployment.yaml
charts/oes/templates/deployments/oes-dashboard-deployment.yaml
charts/oes/templates/deployments/oes-datascience-deployment.yaml
charts/oes/templates/deployments/oes-gate-deployment.yaml
charts/oes/templates/deployments/oes-platform-deployment.yaml
charts/oes/templates/deployments/oes-rabbitmq-deployment.yaml
charts/oes/templates/deployments/oes-sapor-deployment.yaml
charts/oes/templates/deployments/oes-ui-deployment.yaml
charts/oes/templates/deployments/oes-visibility-deployment.yaml
charts/oes/templates/deployments/opa-deployment.yaml
charts/oes/templates/sapor-gate/sapor-gate-secret.yaml
charts/oes/values.yaml

values yaml, custom plugins and deck cros changes 
Releasing 4.0.4.3 helm chart with 4.0.19 version

committed the changes deck cors and custom plugin config

---

charts/oes/values.yaml

https://devopsmx.atlassian.net/browse/OP-22150

Updated ISD and halyard images of v4.isd-spin-2024.06.00 release

---

charts/oes/charts/grafana/dashboards/DeploymentInsight-Grafana v10.2.2 .json

https://devopsmx.atlassian.net/browse/OP-22983

Uid update

---

charts/oes/charts/grafana/dashboards/DeploymentInsight-Grafana v10.2.2 .json

OP-22983 Modified the no. of successful deployments query to display the graph in all time intervals.

OP-22983 Modified the no. of successful deployments query to display the graph in all time intervals.

---

charts/oes/charts/grafana/dashboards/DeploymentInsight-Grafana v10.2.2 .json

https://devopsmx.atlassian.net/browse/OP-22983

update to duration in ms
